=== grahamstark/ada_mill/xml/mill.dtd
<!--
    Propel XML database schema DTD
    $Id: database.dtd,v 1.7 2005/03/30 11:38:18 hlellelid Exp $

    This is based very closely on the schema DTD for Torque, but
    some differences do exist.
-->

<!--

defaultPhpNamingMethod determines how a table or column name,
from the name attribute in the xml database file, is converted to a
PHP class or method name.

     nochange   - indicates not change is performed.
     underscore - Underscores are removed, First letter is
              capitalized, first letter after an underscore
              is capitalized, the rest of the letters are
              converted to lowercase.
     phpname   - same as underscore, but no letters are converted
              to lowercase.
-->

<!ELEMENT database ( adaTypePackage*, adaDataPackage?, table+, schema* )>
<!ATTLIST database
  name           CDATA #REQUIRED
>

<!ELEMENT schema ( table+, adaDataPackage? )>
<!ATTLIST schema
  name           CDATA #REQUIRED
>

<!ELEMENT adaTypePackage EMPTY>
<!ATTLIST adaTypePackage
  name CDATA #REQUIRED
>

<!ELEMENT adaDataPackage EMPTY>
<!ATTLIST adaDataPackage
  name CDATA #REQUIRED
>

<!ELEMENT external-schema EMPTY>
<!ATTLIST external-schema
  filename CDATA #REQUIRED
>

<!--
     note: the interface="true", requires that useManagers=true in the
     properties file.
-->
<!ELEMENT table (localAdaTypePackage*, column+, (foreign-key|index|unique)* )>

<!ATTLIST table
  name            CDATA #REQUIRED
  description     CDATA #IMPLIED
  adaExternalName CDATA #IMPLIED
  defaultInstanceName CDATA #IMPLIED
>

<!ELEMENT column ((inheritance|vendor)*)>

<!ATTLIST column
  name CDATA #REQUIRED
  primaryKey (true|false) "false"
  required (true|false) "false"
  type
    (
          BIT  | INTEGER  | FLOAT | BIGINT
        | REAL | DECIMAL  | CHAR | VARCHAR 
        | DATE | TIME     | TIMESTAMP   
        | DOUBLE | ENUM   | BOOLEAN
    ) "VARCHAR"
  size CDATA #IMPLIED
  scale CDATA #IMPLIED
  default CDATA #IMPLIED
  autoIncrement (true|false) "false"
  description CDATA #IMPLIED
  values CDATA #IMPLIED
  adaTypeName CDATA #IMPLIED
  isArray (true|false) "false" 
  arrayIsExternallyDefined (true|false) "false" 
  arrayFirst CDATA #IMPLIED "1"
  arrayLast CDATA #IMPLIED
  arrayIndexType (ENUM|INTEGER) "INTEGER"
  arrayAdaIndexTypeName CDATA "Positive"
  arrayIndexIsExternallyDefined (true|false) "false" 
  
  arrayEnumValues CDATA #IMPLIED
  arrayName CDATA #IMPLIED
  
>


<!ELEMENT foreign-key (reference+, vendor*)>
<!ATTLIST foreign-key
  foreignTable CDATA #REQUIRED
  name CDATA #IMPLIED
  onUpdate (CASCADE|cascade|SETNULL|setnull|RESTRICT|restrict|NONE|none) "none"
  onDelete (CASCADE|cascade|SETNULL|setnull|RESTRICT|restrict|NONE|none) "none"
>

<!ELEMENT reference EMPTY>
<!ATTLIST reference
  local CDATA #REQUIRED
  foreign CDATA #REQUIRED
>

<!ELEMENT index (index-column+)>
<!ATTLIST index
  name CDATA #IMPLIED
>

<!ELEMENT index-column (vendor*)>
<!ATTLIST index-column
  name CDATA #REQUIRED
  size CDATA #IMPLIED
>

<!ELEMENT unique (unique-column+)>
<!ATTLIST unique
  name CDATA #IMPLIED
>

<!ELEMENT unique-column (vendor*)>
<!ATTLIST unique-column
  name CDATA #REQUIRED
>

=== grahamstark/ada_mill/simple/xml/database-schema.xml
<?xml version="1.0"  encoding="ISO-8859-1"  standalone="no" ?>
<!DOCTYPE database PUBLIC "http://virtual-worlds.biz/Mill"  "http://www.virtual-worlds.biz/dtds/mill.dtd">
<database name="adrs_data">

        <adaTypePackage name='Test_Package' />
        
        <table name="standard_user" description="A user" >
           
                <localAdaTypePackage name='Test_Package' />
                <localAdaTypePackage name='Test_Package_2' />
                <column name="user_id"  
                        primaryKey='true'
                        type='INTEGER'
                        adaTypeName='Integer'
                        description=""/>
                <column name="username"  
                        required="true"
                        default=''
                        type="CHAR"
                        size="16"
                        description=""/>
                <column name='password'
                        default=''
                        type='CHAR'
                        size='32' />
                <column name='type1'
                        type='ENUM'
                        adaTypeName='An_Enum'
                        />
                <column name='type2'
                        type='ENUM'
                        values='v1 v2 v3'
                        />
                        
                <column name='date_created'
                        type='DATE'
                        default='0000-00-00'
                         />
        </table>

        <table name="standard_group" description="Group a user belongs to">        
                <column name="name"
                        type='CHAR'
                        size='30'
                        primaryKey='true'
                        default='SATTSIM'
                        description="Model Name"/>
                <column name="description"
                        type='CHAR'
                        size='120'
                        description="Description"/>
        </table>
        
        <table name="group_members" description="Group a user belongs to">        
                <column name="group_name"
                        type='CHAR'
                        size='30'
                        primaryKey='true'
                        default=''
                        description="Model Name"/>
                <column name="user_id"  
                        primaryKey='true'
                        type='INTEGER'
                        description=""/>
                <foreign-key foreignTable="standard_group"   onDelete="CASCADE">
                     <reference foreign="name" local="group_name"/>
                </foreign-key>
                <foreign-key foreignTable="standard_user"   onDelete="CASCADE">
                     <reference foreign="user_id" local="user_id"/>
                </foreign-key>
        </table>
</database>

=== grahamstark/ada_mill/simple_pg/xml/database-schema.xml
<?xml version="1.0"  encoding="ISO-8859-1"  standalone="no" ?>
<!DOCTYPE database PUBLIC "http://virtual-worlds.biz/Mill"  "http://www.virtual-worlds.biz/dtds/mill.dtd">
<database name="adrs_data">
        
        <table name="standard_user" description="A user" >
           
                <column name="user_id"  
                        primaryKey='true'
                        type='INTEGER'
                        adaTypeName='Integer'
                        description=""/>
                <column name="username"  
                        required="true"
                        default=''
                        type="CHAR"
                        size="16"
                        description=""/>
                <column name='password'
                        default=''
                        type='CHAR'
                        size='32' />
                <column name='type1'
                        type='ENUM'
                        values='a3 b4 c5'
                        />
                <column name='type2'
                        type='ENUM'
                        values='v1 v2 v3'
                        />
                <column name='a_bigint' type='BIGINT'/>
                <column name='a_real' type='REAL'/>
                <column name='a_decimal' type='DECIMAL' size='12' scale='2'/>
                <column name='a_double' type='DOUBLE'/>
                <column name='a_boolean' type='BOOLEAN'/>
                <column name='a_varchar' type='VARCHAR' size='200'/>
                <column name='a_date'
                        type='DATE'
                        default='0000-00-00'
                         />
        </table>

        <table name="standard_group" description="Group a user belongs to">        
                <column name="name"
                        type='CHAR'
                        size='30'
                        primaryKey='true'
                        default='SATTSIM'
                        description="Model Name"/>
                <column name="description"
                        type='CHAR'
                        size='120'
                        description="Description"/>
        </table>
        
        <table name="group_members" description="Group a user belongs to">        
                <column name="group_name"
                        type='CHAR'
                        size='30'
                        primaryKey='true'
                        default=''
                        description="Model Name"/>
                <column name="user_id"  
                        primaryKey='true'
                        type='INTEGER'
                        description=""/>
                <foreign-key foreignTable="standard_group"   onDelete="CASCADE">
                     <reference foreign="name" local="group_name"/>
                </foreign-key>
                <foreign-key foreignTable="standard_user"   onDelete="CASCADE">
                     <reference foreign="user_id" local="user_id"/>
                </foreign-key>
        </table>
</database>

=== grahamstark/ada_mill/dev/xml/database-schema.xml
<?xml version="1.0" 
      encoding="ISO-8859-1" 
      standalone="no"
       ?>
<!DOCTYPE database SYSTEM "http://www.virtual-worlds.biz/dtds/mill.dtd">
<database name="adrs_data">

        <table name="standard_user" description="A user">
           
                <column name="user_id"  
                        primaryKey='true'
                        type='INTEGER'
                        description=""/>
                <column name="username"  
                        required="true"
                        default=''
                        type="CHAR"
                        size="16"
                        description=""/>
                <column name='password'
                        default=''
                        type='CHAR'
                        size='32' />
                <column name='salary'
                        default=''
                        type='DECIMAL'
                        size='10'
                        scale='2' />
                <column name='rate'
                        default=''
                        type='REAL'
                        />
                        
                <column name='date_created'
                        type='DATE'
                        default='0000-00-00'
                         />
        </table>

        <table name="standard_group" description="Group a user belongs to">        
                <column name="name"
                        type='CHAR'
                        size='30'
                        primaryKey='true'
                        default='SATTSIM'
                        description="Model Name"/>
                <column name="description"
                        type='CHAR'
                        size='120'
                        description="Description"/>
        </table>
        
        <table name="group_members" description="Group a user belongs to">        
                <column name="group_name"
                        type='CHAR'
                        size='30'
                        primaryKey='true'
                        default=''
                        description="Model Name"/>
                <column name="user_id"  
                        primaryKey='true'
                        type='INTEGER'
                        description=""/>
                <foreign-key foreignTable="standard_group"   onDelete="CASCADE">
                     <reference foreign="name" local="group_name"/>
                </foreign-key>
                <foreign-key foreignTable="standard_user"   onDelete="CASCADE">
                     <reference foreign="user_id" local="user_id"/>
                </foreign-key>
        </table>
</database>
